services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/CookingRecipes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123454321
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=CookingRecipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123454321
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 